# This ConfigMap is used to configure a self-hosted pan CNI installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: pan-cni-config
  namespace: kube-system
data:
  # The CNI network configuration to add to the plugin chain on each node.  The special
  # values in this config will be automatically populated.
  # Some sample options other than the default (follow them by ',' where applicable).
  #           "security_namespaces": [ "kube-system", "pan-system"]
  #        "mode": "teardown"
  cni_network_config: |-
        {
          "name": "pan-cni",
          "type": "pan-cni",
          "log_level": "debug",
          "appinfo_dir": "/var/log/pan-appinfo",
          "mode": "daemonset",
          "firewall": [ "pan-fw" ],
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__",
              "cni_bin_dir": "/opt/cni/bin",
              "exclude_namespaces": [ ],
              "security_namespaces": [ "kube-system"]
          }
        }
